### ISSUE TITLE
Arukasでhttps接続が502エラーになる

### ISSUE THREAD

**Issue by tukiyo** [u-ryo/docker_alpine_sshd#2]
はじめまして、素敵な試みですね。

私が試したところ、残念ながらendpointで表示されているhttpsのURLにアクセスのたびに
以下表示となります。

* 502 Bad Gateway
* SSH-2.0-OpenSSH_7.9 （たまにこちらが表示される。※これはArukas側の問題？？）

u-ryoさんはうまく行きますか？
また、その場合の PROXY_PASS値 も教えていただけたらこちらでも動作確認したいです。

**Comment by u-ryo** [comment]
初めまして。
まさかこのような使い方をする人が他にもいるとは思っていませんでした。
言われて改めて久し振りに試してみたのですが、電話認証が必須になったようで、電話認証に何故か失敗してしまい(何度やっても「認証コードが不正です」)、アプリがデプロイ中のままでうまく試せません。
`PROXY_PASS`値はdefaultの`https://google.com`でもいい筈なのですが、どうでしょうか。
あとは、「Portの指定は、80番TCPを1番目に、22番TCPを2番目に、それ以外の指定はなし」にしているかを確認してみて下さい。あー、この情報がREADMEにあるべきでしたでしょうか。
Helpで質問を投げると、中の人が結構丁寧に答えてくれます(私はcodeも書いてもらえました)。

**Comment by tukiyo** [comment]
> Portの指定は、80番TCPを1番目に、22番TCPを2番目に

この方法で解決しました😆ありがとうございます。

**Comment by u-ryo** [comment]
試して下さりありがとうございました。
うまく行ったようで何よりです。
`Port`設定のことをREADMEに載せました。
`PROXY_PASS`のdefault値もgoogleではうまく行かないようになっていましたので変えました。
